package Model;
// Generated 14/09/2021 08:00:16 PM by Hibernate Tools 4.3.1



/**
 * Enfermeros generated by hbm2java
 */
public class Enfermeros  implements java.io.Serializable {


     private Integer idEnfermero;
     private Areas areas;
     private Hospitales hospitales;
     private String nombreEnfermero;
     private String apaternoEnfermero;
     private String amaternoEnfermero;
     private String sexoEnfermero;
     private Integer edadEnfermero;
     private String telefonoEnfermero;
     private String direccionEnfermero;
     private String correoEnfermero;
     private String tipoEnfermero;
     private Double sueldoEnfermero;

    public Enfermeros() {
    }

    public Enfermeros(Areas areas, Hospitales hospitales, String nombreEnfermero, String apaternoEnfermero, String amaternoEnfermero, String sexoEnfermero, Integer edadEnfermero, String telefonoEnfermero, String direccionEnfermero, String correoEnfermero, String tipoEnfermero, Double sueldoEnfermero) {
       this.areas = areas;
       this.hospitales = hospitales;
       this.nombreEnfermero = nombreEnfermero;
       this.apaternoEnfermero = apaternoEnfermero;
       this.amaternoEnfermero = amaternoEnfermero;
       this.sexoEnfermero = sexoEnfermero;
       this.edadEnfermero = edadEnfermero;
       this.telefonoEnfermero = telefonoEnfermero;
       this.direccionEnfermero = direccionEnfermero;
       this.correoEnfermero = correoEnfermero;
       this.tipoEnfermero = tipoEnfermero;
       this.sueldoEnfermero = sueldoEnfermero;
    }
   
    public Integer getIdEnfermero() {
        return this.idEnfermero;
    }
    
    public void setIdEnfermero(Integer idEnfermero) {
        this.idEnfermero = idEnfermero;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public Hospitales getHospitales() {
        return this.hospitales;
    }
    
    public void setHospitales(Hospitales hospitales) {
        this.hospitales = hospitales;
    }
    public String getNombreEnfermero() {
        return this.nombreEnfermero;
    }
    
    public void setNombreEnfermero(String nombreEnfermero) {
        this.nombreEnfermero = nombreEnfermero;
    }
    public String getApaternoEnfermero() {
        return this.apaternoEnfermero;
    }
    
    public void setApaternoEnfermero(String apaternoEnfermero) {
        this.apaternoEnfermero = apaternoEnfermero;
    }
    public String getAmaternoEnfermero() {
        return this.amaternoEnfermero;
    }
    
    public void setAmaternoEnfermero(String amaternoEnfermero) {
        this.amaternoEnfermero = amaternoEnfermero;
    }
    public String getSexoEnfermero() {
        return this.sexoEnfermero;
    }
    
    public void setSexoEnfermero(String sexoEnfermero) {
        this.sexoEnfermero = sexoEnfermero;
    }
    public Integer getEdadEnfermero() {
        return this.edadEnfermero;
    }
    
    public void setEdadEnfermero(Integer edadEnfermero) {
        this.edadEnfermero = edadEnfermero;
    }
    public String getTelefonoEnfermero() {
        return this.telefonoEnfermero;
    }
    
    public void setTelefonoEnfermero(String telefonoEnfermero) {
        this.telefonoEnfermero = telefonoEnfermero;
    }
    public String getDireccionEnfermero() {
        return this.direccionEnfermero;
    }
    
    public void setDireccionEnfermero(String direccionEnfermero) {
        this.direccionEnfermero = direccionEnfermero;
    }
    public String getCorreoEnfermero() {
        return this.correoEnfermero;
    }
    
    public void setCorreoEnfermero(String correoEnfermero) {
        this.correoEnfermero = correoEnfermero;
    }
    public String getTipoEnfermero() {
        return this.tipoEnfermero;
    }
    
    public void setTipoEnfermero(String tipoEnfermero) {
        this.tipoEnfermero = tipoEnfermero;
    }
    public Double getSueldoEnfermero() {
        return this.sueldoEnfermero;
    }
    
    public void setSueldoEnfermero(Double sueldoEnfermero) {
        this.sueldoEnfermero = sueldoEnfermero;
    }




}


