package Model;
// Generated 14/09/2021 08:00:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Historiales generated by hbm2java
 */
public class Historiales  implements java.io.Serializable {


     private Integer idHistorial;
     private String tipoEnfermedad;
     private String descripcion;
     private Date entrada;
     private Date salida;
     private Set<Pacientes> pacienteses = new HashSet<Pacientes>(0);

    public Historiales() {
    }

    public Historiales(String tipoEnfermedad, String descripcion, Date entrada, Date salida, Set<Pacientes> pacienteses) {
       this.tipoEnfermedad = tipoEnfermedad;
       this.descripcion = descripcion;
       this.entrada = entrada;
       this.salida = salida;
       this.pacienteses = pacienteses;
    }
   
    public Integer getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(Integer idHistorial) {
        this.idHistorial = idHistorial;
    }
    public String getTipoEnfermedad() {
        return this.tipoEnfermedad;
    }
    
    public void setTipoEnfermedad(String tipoEnfermedad) {
        this.tipoEnfermedad = tipoEnfermedad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Date entrada) {
        this.entrada = entrada;
    }
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }
    public Set<Pacientes> getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set<Pacientes> pacienteses) {
        this.pacienteses = pacienteses;
    }




}


