package Model;
// Generated 14/09/2021 08:00:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hospitales generated by hbm2java
 */
public class Hospitales  implements java.io.Serializable {


     private Integer idHospital;
     private Integer numeroHospital;
     private String nombrHospital;
     private String direccionHospital;
     private String telefonoHospital;
     private String tipoHospital;
     private Set<Doctores> doctoreses = new HashSet<Doctores>(0);
     private Set<Enfermeros> enfermeroses = new HashSet<Enfermeros>(0);
     private Set<Pacientes> pacienteses = new HashSet<Pacientes>(0);

    public Hospitales() {
    }

    public Hospitales(Integer numeroHospital, String nombrHospital, String direccionHospital, String telefonoHospital, String tipoHospital, Set<Doctores> doctoreses, Set<Enfermeros> enfermeroses, Set<Pacientes> pacienteses) {
       this.numeroHospital = numeroHospital;
       this.nombrHospital = nombrHospital;
       this.direccionHospital = direccionHospital;
       this.telefonoHospital = telefonoHospital;
       this.tipoHospital = tipoHospital;
       this.doctoreses = doctoreses;
       this.enfermeroses = enfermeroses;
       this.pacienteses = pacienteses;
    }
   
    public Integer getIdHospital() {
        return this.idHospital;
    }
    
    public void setIdHospital(Integer idHospital) {
        this.idHospital = idHospital;
    }
    public Integer getNumeroHospital() {
        return this.numeroHospital;
    }
    
    public void setNumeroHospital(Integer numeroHospital) {
        this.numeroHospital = numeroHospital;
    }
    public String getNombrHospital() {
        return this.nombrHospital;
    }
    
    public void setNombrHospital(String nombrHospital) {
        this.nombrHospital = nombrHospital;
    }
    public String getDireccionHospital() {
        return this.direccionHospital;
    }
    
    public void setDireccionHospital(String direccionHospital) {
        this.direccionHospital = direccionHospital;
    }
    public String getTelefonoHospital() {
        return this.telefonoHospital;
    }
    
    public void setTelefonoHospital(String telefonoHospital) {
        this.telefonoHospital = telefonoHospital;
    }
    public String getTipoHospital() {
        return this.tipoHospital;
    }
    
    public void setTipoHospital(String tipoHospital) {
        this.tipoHospital = tipoHospital;
    }
    public Set<Doctores> getDoctoreses() {
        return this.doctoreses;
    }
    
    public void setDoctoreses(Set<Doctores> doctoreses) {
        this.doctoreses = doctoreses;
    }
    public Set<Enfermeros> getEnfermeroses() {
        return this.enfermeroses;
    }
    
    public void setEnfermeroses(Set<Enfermeros> enfermeroses) {
        this.enfermeroses = enfermeroses;
    }
    public Set<Pacientes> getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set<Pacientes> pacienteses) {
        this.pacienteses = pacienteses;
    }




}


