package Model;
// Generated 14/09/2021 08:00:16 PM by Hibernate Tools 4.3.1



/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer idPaciente;
     private Historiales historiales; //Instertar metodo constructor
     private Hospitales hospitales; //Instertar metodo constructor
     private String nombrePaciente;
     private String apaternoPaciente;
     private String amaternoPaciente;
     private String sexoPaciente;
     private Integer edadPaciente;
     private String telefonoaciente;
     private String direccionPaciente;

    public Pacientes() 
    {
        //IMPORTANTE (FOREING KEY)
        //Tendremos que poner instancia de la llave que vamos a relacionar con esta tabla (Alumnos) y asi hacer uso de la llave foranea 
        
        historiales = new Historiales();
        hospitales = new Hospitales();
    }

    public Pacientes(Historiales historiales, Hospitales hospitales, String nombrePaciente, String apaternoPaciente, String amaternoPaciente, String sexoPaciente, Integer edadPaciente, String telefonoaciente, String direccionPaciente) {
       this.historiales = historiales;
       this.hospitales = hospitales;
       this.nombrePaciente = nombrePaciente;
       this.apaternoPaciente = apaternoPaciente;
       this.amaternoPaciente = amaternoPaciente;
       this.sexoPaciente = sexoPaciente;
       this.edadPaciente = edadPaciente;
       this.telefonoaciente = telefonoaciente;
       this.direccionPaciente = direccionPaciente;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Historiales getHistoriales() {
        return this.historiales;
    }
    
    public void setHistoriales(Historiales historiales) {
        this.historiales = historiales;
    }
    public Hospitales getHospitales() {
        return this.hospitales;
    }
    
    public void setHospitales(Hospitales hospitales) {
        this.hospitales = hospitales;
    }
    public String getNombrePaciente() {
        return this.nombrePaciente;
    }
    
    public void setNombrePaciente(String nombrePaciente) {
        this.nombrePaciente = nombrePaciente;
    }
    public String getApaternoPaciente() {
        return this.apaternoPaciente;
    }
    
    public void setApaternoPaciente(String apaternoPaciente) {
        this.apaternoPaciente = apaternoPaciente;
    }
    public String getAmaternoPaciente() {
        return this.amaternoPaciente;
    }
    
    public void setAmaternoPaciente(String amaternoPaciente) {
        this.amaternoPaciente = amaternoPaciente;
    }
    public String getSexoPaciente() {
        return this.sexoPaciente;
    }
    
    public void setSexoPaciente(String sexoPaciente) {
        this.sexoPaciente = sexoPaciente;
    }
    public Integer getEdadPaciente() {
        return this.edadPaciente;
    }
    
    public void setEdadPaciente(Integer edadPaciente) {
        this.edadPaciente = edadPaciente;
    }
    public String getTelefonoaciente() {
        return this.telefonoaciente;
    }
    
    public void setTelefonoaciente(String telefonoaciente) {
        this.telefonoaciente = telefonoaciente;
    }
    public String getDireccionPaciente() {
        return this.direccionPaciente;
    }
    
    public void setDireccionPaciente(String direccionPaciente) {
        this.direccionPaciente = direccionPaciente;
    }




}


